### ISSUE TITLE
Publish OpenFeature.Contrib.Providers.Flagsmith 0.1.2 version

### ISSUE THREAD

**Issue by vpetrusevici** [open-feature/dotnet-sdk-contrib#104]
Hi!
Can you publish the last release of OpenFeature.Contrib.Providers.Flagsmith in nuget please?
For some reason it wasn't done automatically

**Comment by toddbaert** [comment]
Looks like there's still some issue: Providers.Flagsmith.0.1.0.nupkg' already exists at feed

**Comment by vpetrusevici** [comment]
Here? https://github.com/open-feature/dotnet-sdk-contrib/blob/main/src/OpenFeature.Contrib.Providers.Flagsmith/OpenFeature.Contrib.Providers.Flagsmith.csproj

**Comment by toddbaert** [comment]
> Here? https://github.com/open-feature/dotnet-sdk-contrib/blob/main/src/OpenFeature.Contrib.Providers.Flagsmith/OpenFeature.Contrib.Providers.Flagsmith.csproj

Ya, I just found that. The release-please annotation must be on the same line as the version: https://github.com/open-feature/dotnet-sdk-contrib/pull/107

**Comment by toddbaert** [comment]
@vpetrusevici `Your package was pushed.`

Sorry about that!

**Comment by toddbaert** [comment]
https://www.nuget.org/packages/OpenFeature.Contrib.Providers.Flagsmith/0.1.4

**Comment by vpetrusevici** [comment]
Nice!
No problem. Thank you for help!
