### ISSUE TITLE
flagd dependencies on Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by ghelyar** [open-feature/dotnet-sdk-contrib#232]
I don't think `OpenFeature.Contrib.Providers.Flagd` should depend on `Microsoft.Extensions.Logging`, `Microsoft.Extensions.Logging.Console` or `Microsoft.Extensions.Logging.Debug`.

As well as them just being extra dependencies on the package, the consuming application should really be defining where the logs go, rather than the library.

It could maybe depend on `Microsoft.Extensions.Logging.Abstractions` by taking an `ILogger`, `ILogger<T>` or `ILoggerFactory` in the `InProcessResolver` constructor and passing it through (the OpenFeature SDK itself can take an `ILogger?`), but it could also just be removed entirely for now as it's only used for two small pieces of debug logging.

At the moment
- `StringEvaluator` creates a logger in its constructor but does not use it afterwards.
- `SemVerEvaluator` logs a debug message when catching exceptions from `SemVersion.Parse`, but it could just use `SemVersion.TryParse` instead if it did not do this logging, and avoid the throw and catch. RPC mode does not log anything here.
- `FractionalEvaluator` uses it to debug log "no matching bucket found" but it isn't really necessary to log that and it already gives a reason of `DEFAULT` on the details result. RPC mode does not log anything here.

Here's an example of a commit that would just remove it entirely: https://github.com/open-feature/dotnet-sdk-contrib/commit/8c4875b253abca02f18b52e5f3ff5ccb409da0f8

**Comment by toddbaert** [comment]
I fully agree with this.

@ghelyar if you want to open a PR I will accept it.

Otherwise we can keep this issue open for others.
