### ISSUE TITLE
[flagd-provider] Implement Unix socket support

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk-contrib#35]
Implement a unix socket connection support for flagd, similar to the [Java](https://github.com/open-feature/java-sdk-contrib/blob/103fe68da6f1947d97a2f33363cff16b7dd50ec1/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java#L116-L122) and [JS](https://github.com/open-feature/js-sdk-contrib/blob/main/libs/providers/flagd/src/lib/service/grpc/service.ts#L99) implementations, using similar configuration paradigms.

Dependent on https://github.com/open-feature/dotnet-sdk-contrib/pull/31

**Comment by bacherfl** [comment]
@toddbaert If it's ok I would like to work on this after #31 has been merged

**Comment by toddbaert** [comment]
Absolutely. Looks like @beeme1mr has assigned you.

**Comment by toddbaert** [comment]
It's confusing, but netstandard2.0 is the intersection (in set-theory teams) of few different APIs and is probably the right choice for a project like ours. [It encompasses .NET 5.0](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#select-net-standard-version).

>We recommend you target .NET Standard 2.0, unless you need to support an earlier version. Most general-purpose libraries should not need APIs outside of .NET Standard 2.0. .NET Standard 2.0 is supported by all modern platforms and is the recommended way to support multiple platforms with one target.

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#which-net-standard-version-to-target

**Comment by benjiro** [comment]
We will have to multi-target that project to use the new functionality in net6.0(net5.0 is EOL) above. As you stated, just use preprocessor to define the specific logic. Netstandard is basically dead now it was used to help with getting over to .net core(now .net). Many people targeting full framework still probably won't be using GRPC, since they haven't moved onto .net gravy train yet 😄

**Comment by bacherfl** [comment]
Thanks @toddbaert and @benjiro for your answers, that made it clearer for me :) I'm already working on the PR for this issue and will keep you updated!

**Comment by toddbaert** [comment]
Ahh, well I learned something here too then! I think Microsoft may have some docs to update.

**Comment by beeme1mr** [comment]
> since they haven't moved onto .net gravy train yet

🚋All aboard the gravy train 😄

**Comment by bacherfl** [comment]
Alright, the PR seems to be ready for a first review round :) #42 
I hope I did align with the best practices when it comes to handling different target frameworks in dotnet, but if there is something that should be done differently, please let me know
