### ISSUE TITLE
[flagd-provider] Implement TLS connection

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk-contrib#36]
Implement TLS connection for the provider, using similar configuration paradigms to other language implementations (see [Java](https://github.com/open-feature/java-sdk-contrib/tree/main/providers/flagd#usage) example).

Depend on https://github.com/open-feature/dotnet-sdk-contrib/pull/31

**Comment by odubajDT** [comment]
I would like to take this ticket of possible

**Comment by toddbaert** [comment]
@odubajDT assigned
