### ISSUE TITLE
[flagd-provider] Implement standard caching, with LRU cache

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk-contrib#37]
Implement [standard flagd caching](https://github.com/open-feature/flagd/blob/main/docs/other_resources/caching.md). Use a LRU cache implementation such as [caffeine](https://github.com/ben-manes/caffeine) or similar. The cache requires a persistent connection to the flagd event stream. The stream should reconnect automatically if broken, and purge entries if change events are received or the connection fails.

See [JS](https://github.com/open-feature/js-sdk-contrib/blob/7401481c75416283c134184bc41f5b89dcb0ec49/libs/providers/flagd/src/lib/service/grpc/service.ts#L78) or [Java](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdCache.java) implementation for reference.

Depends on: https://github.com/open-feature/dotnet-sdk-contrib/pull/31

**Comment by bacherfl** [comment]
@toddbaert I would like to work on this one :)

**Comment by toddbaert** [comment]
> @toddbaert I would like to work on this one :)

assigned!
