### ISSUE TITLE
[Otel Hook] Add metrics hook to OpenFeature.Contrib.Hooks.Otel

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk-contrib#70]
We should add a metrics hook to OpenFeature.Contrib.Hooks.Otel.

Similar to other implementations, this should be a breaking change to make the pruposes of each hook clearer. `OtelHook` should be renamed to `TracingHook`, and a new `MetricsHook` should be added.

export const ACTIVE_COUNT_NAME = `${FEATURE_FLAG}.evaluation_active_count`;
export const REQUESTS_TOTAL_NAME = `${FEATURE_FLAG}.evaluation_requests_total`;
export const SUCCESS_TOTAL_NAME = `${FEATURE_FLAG}.evaluation_success_total`;
export const ERROR_TOTAL_NAME = `${FEATURE_FLAG}.evaluation_error_total`;

Metrics hook requirements:
- should add 4 metrics (`feature_flag.evaluation_active_count, feature_flag.evaluation_requests_total, feature_flag.evaluation_success_total, feature_flag.evaluation_error_total`), similar to the [JS](https://github.com/open-feature/js-sdk-contrib/blob/main/libs/hooks/open-telemetry/src/lib/metrics/metrics-hook.ts) / [Java](https://github.com/open-feature/java-sdk-contrib/blob/main/hooks/open-telemetry/src/main/java/dev/openfeature/contrib/hooks/otel/MetricsHook.java) / [Go](https://github.com/open-feature/go-sdk-contrib/blob/main/hooks/open-telemetry/pkg/metrics.go) implementations
- support a functional means of adding custom attributes to metrics, as in the [JS implementation](https://github.com/open-feature/js-sdk-contrib/tree/main/libs/hooks/open-telemetry#custom-metric-attributes), which allows consumers to provide a function that takes the flag metadata and returns OTel attributes

- [x] #112
- [x] #113

**Comment by askpt** [comment]
@toddbaert can we split this issue into two separate issues?
1. Rename `OtelHook` into `TracingHook`
2. Create a new `MetricsHook`

About point 1, should we keep a "dummy" `OtelHook` and mark it as deprecated and it will be removed in a later version? Or just rename and the consumers will break upon update?

**Comment by askpt** [comment]
@toddbaert this can be closed since #118 exists now :)
