### ISSUE TITLE
[flagd-provider] FlagdProvider constructor which takes only Uri will throw object null reference

### ISSUE THREAD

**Issue by arthurchzi** [open-feature/dotnet-sdk-contrib#71]
FlagdProvider(Uri url) does not initialize _config object hence using this constructor will leave _config null and throw exception.

**Comment by toddbaert** [comment]
Yes, this definitely seems to be the case.

We should fix this, add a test, and also reduce the duplication across the constructors, if possible.

**Comment by toddbaert** [comment]
Fixed with release: https://github.com/open-feature/dotnet-sdk-contrib/pull/85
