### ISSUE TITLE
[Flagd provider] Provider fails when used with a .net framework 4.6.2+ project

### ISSUE THREAD

**Issue by Wolftousen** [open-feature/dotnet-sdk-contrib#73]
Was trying to use this with a .net framework 4.8 project yesterday and found that no matter what I did, I would get a GRPC error.

After some digging, I found this [documentation](https://learn.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-7.0#net-framework) from Microsoft about .net framework projects requiring TLS for GRPC to work.

Examining the code, this is currently impossible due to the .net framework path of the TLS code not being implemented yet and just throwing an exception instead.

Reproduce steps:
1. Run the Flagd server in Docker with a self signed cert
2. Create a .Net Framework 4.8 console application that references this project and evaluates one of the test bool flags
3. Run the console application with TLS enabled and the self signed cert supplied (both through the env vars)
4. Notice that the application fails when it attempts to get the flag evaulation
5. TLS without the self signed cert fails for other reasons

**Comment by toddbaert** [comment]
This was fixed with https://github.com/open-feature/dotnet-sdk-contrib/pull/72
