### ISSUE TITLE
[Flagsmith provider] Initial implementation

### ISSUE THREAD

**Issue by vpetrusevici** [open-feature/dotnet-sdk-contrib#90]
Hi!
I tried to implement Flagsmith provider.
Can somebody make a code review?
https://github.com/open-feature/dotnet-sdk-contrib/pull/89
Thanks :)

**Comment by vpetrusevici** [comment]
Guys, tell me please when can we expect the release?

**Comment by toddbaert** [comment]
@vpetrusevici as soon as we merge [this](https://github.com/open-feature/dotnet-sdk-contrib/pull/93). Please add your approval (once you accept your invite to the org, you will be automatically added to such PRs).

**Comment by vpetrusevici** [comment]
Sorry. I don't have rights for approve

**Comment by toddbaert** [comment]
Closing since we've released: https://www.nuget.org/packages/OpenFeature.Contrib.Providers.Flagsmith
